branchName: '${issue.number}-${issue.body[-20]}'
gitSafeReplacementChar: ""
openDraftPR: true
autoCloseIssue: true
branches:
  - label: 
    - feature
    - backend
    prefix: be-
    name: be/develop
  - label:
    - feature
    - frontend
    prefix: fe-
    name: fe/develop
  - label: '*'
    skip: true
  # - label: docs
  #   prefix: docs/
  # - label: hotfix
  #   prefix: hotfix/
  # - label: refactor
  #   prefix: refactor/
  # - label: chore
  #   prefix: chore/
  # - label: release
  #   prefix: release/
  # - label: test
  #   prefix: test/
  # - label: fix
  #   prefix: fix/
commentMessage: 'Branch명 ${branchName}이 생성되었습니다. \\n 현재 이슈 (${issue.title})에 연결되어 [Draft PR](${issue.pull_request.url})이 생성되었습니다. \\n 작업이 완료된 후, `Ready To Review` 버튼을 눌러주세요 :) '
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
 
