version: '3.8'

services:
  application:
    container_name: app_container
    platform: linux/arm64
    restart: always
    image: ${DOCKER_REPO_NAME}/cruru:${DOCKER_IMAGE_TAG}
    ports:
      - ${SERVER_BINDING_PORT}
      - ${MONITORING_BINDING_PORT}
    env_file:
      - .env
    environment:
      PROFILE: prod
    networks:
      cruru_network:
        ipv4_address: ${APP_IP_ADDRESS}

networks:
  cruru_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
