version: '3.8'

services:
  database-mysql:
    container_name: database-container
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${MYSQL_TIME_ZONE}
    ports:
      - ${DB_PORT}
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_0900_ai_ci'
    networks:
      cruru_network:
        ipv4_address: ${DB_IP_ADDRESS}

  application:
    container_name: app_container
    platform: linux/arm64
    depends_on:
      - database-mysql
    restart: always
    image: ${DOCKER_REPO_NAME}/cruru:${DOCKER_IMAGE_VERSION_TAG}
    ports:
      - ${SERVER_BINDING_PORT}
      - ${MONITORING_BINDING_PORT}
    env_file:
      - .env
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
    volumes:
      - "./log:/log"
    networks:
      cruru_network:
        ipv4_address: ${APP_IP_ADDRESS}

  promtail:
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE_ADDR_LOKI_PORT: ${MONITORING_INSTANCE_ADDR_LOKI_PORT}
      MONITORING_PROFILE: ${MONITORING_PROFILE}
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - "./log:/log"
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    networks:
      cruru_network:
        ipv4_address: 172.18.0.4

networks:
  cruru_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
