version: '3.8'

services:
  application:
    container_name: app_container
    platform: linux/arm64
    restart: always
    image: ${DOCKER_REPO_NAME}/cruru:prod-latest
    ports:
      - ${SERVER_BINDING_PORT}
      - ${MONITORING_BINDING_PORT}
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO}
      SERVER_PORT: ${SERVER_PORT}
      DOCKER_REPO_NAME: ${DOCKER_REPO_NAME}
      MONITORING_PORT: ${MONITORING_PORT}
      MONITORING_BASE_PATH: ${MONITORING_BASE_PATH}
    networks:
      cruru_network:
        ipv4_address: ${APP_IP_ADDRESS}

networks:
  cruru_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
