version: '3.8'
services:
  app_container-blue:
    container_name: app_container-blue
    platform: linux/arm64
    restart: always
    image: cruru/cruru:${DOCKER_IMAGE_VERSION_TAG}
    ports:
      - ${BLUE_SERVER_BINDING_PORT}
      - ${BLUE_MONITORING_BINDING_PORT}
    env_file:
      - .env
    environment:
      SERVER_PORT: ${BLUE_SERVER_PORT}
      PROFILE: test
      TZ: Asia/Seoul
    volumes:
      - "./log:/log"
    networks:
      - cruru_network

  app_container-green:
    container_name: app_container-green
    platform: linux/arm64
    restart: always
    image: cruru/cruru:${DOCKER_IMAGE_VERSION_TAG}
    ports:
      - ${GREEN_SERVER_BINDING_PORT}
      - ${GREEN_MONITORING_BINDING_PORT}
    env_file:
      - .env
    environment:
      SERVER_PORT: ${GREEN_SERVER_PORT}
      PROFILE: test
      TZ: Asia/Seoul
    volumes:
      - "./log:/log"
    networks:
      - cruru_network

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    networks:
      - cruru_network

  promtail:
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE_ADDR_LOKI_PORT: ${MONITORING_INSTANCE_ADDR_LOKI_PORT}
      MONITORING_PROFILE: ${MONITORING_PROFILE}
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - "./log:/log"
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    networks:
      - cruru_network

networks:
  cruru_network:
    external: true
