version: '3.8'

services:
  application:
    container_name: app_container
    platform: linux/arm64
    restart: always
    image: ${DOCKER_REPO_NAME}/cruru:${DOCKER_IMAGE_VERSION_TAG}
    ports:
      - ${SERVER_BINDING_PORT}
      - ${MONITORING_BINDING_PORT}
    env_file:
      - .env
    environment:
      PROFILE: test
      TZ: Asia/Seoul
    volumes:
      - "./log:/log"
    networks:
      cruru_network:
        ipv4_address: ${APP_IP_ADDRESS}

  promtail:
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE_ADDR_LOKI_PORT: ${MONITORING_INSTANCE_ADDR_LOKI_PORT}
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - "./log:/log"
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    networks:
      cruru_network:
        ipv4_address: 172.18.0.4

networks:
  cruru_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
