server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${MONITORING_INSTANCE_ADDR_LOKI_PORT}/loki/api/v1/push"

scrape_configs:
  - job_name: error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ${MONITORING_PROFILE}_error_logs
          __path__: /log/error/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            requestId: requestId
            requestUri: requestUri
            requestMethod: requestMethod
            statusCode: statusCode
            sourceClass: sourceClass
            sourceMethod: sourceMethod
            msg: message
            environment: environment
      - labels:
          level:
          requestUri:
          environment:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000
          location: "Asia/Seoul"

  - job_name: info_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ${MONITORING_PROFILE}_info_logs
          __path__: /log/info/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            requestId: requestId
            requestUri: requestUri
            requestMethod: requestMethod
            statusCode: statusCode
            sourceClass: sourceClass
            sourceMethod: sourceMethod
            msg: message
            environment: environment
      - labels:
          level:
          requestUri:
          environment:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000
          location: "Asia/Seoul"


  - job_name: warn_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ${MONITORING_PROFILE}_warn_logs
          __path__: /log/warn/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            requestId: requestId
            requestUri: requestUri
            requestMethod: requestMethod
            statusCode: statusCode
            sourceClass: sourceClass
            sourceMethod: sourceMethod
            msg: message
            environment: environment
      - labels:
          level:
          requestUri:
          environment:
      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000
          location: "Asia/Seoul"

  - job_name: http_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ${MONITORING_PROFILE}_http_logs
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>[^\s]+) - - \[(?P<timestamp>[^\]]+)\] "(?P<method>[A-Z]+) (?P<request>[^ ]+) HTTP/[^"]+" (?P<status>\d+) (?P<body_bytes_sent>\d+)'
