name: BE/DOCS - API Docs Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: be/develop

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Latest
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build RestDocs with Gradle
        run: ./gradlew asciidoctor

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./build/docs/asciidoc

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build-docs
    steps:
      - name: Deploy API Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
