name: BE/CD - Build & Dev 서버 Deploy

on:
  workflow_dispatch:
  push:
    branches: be/main

jobs:
  build:
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-write-only: true

      - name: Build project using Gradle
        run: ./gradlew bootJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cruru-be-develop-jar
          path: ${{ github.workspace }}/backend/build/libs/cruru-0.0.1-SNAPSHOT.jar

  deploy:
    defaults:
      run:
        working-directory: ./backend
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: cruru-be-develop-jar
          path: ${{ github.workspace }}/backend/build/libs

      - name: Check if cruru API server is running on port 8080
        id: check-server-on-port
        run: |
          echo "Checking if port 8080 is in use..."
          PID=$(lsof -t -i:8080 || true)
          if [ -n "$PID" ]; then
            echo "server_running=true" >> $GITHUB_ENV
            echo "PID=$PID" >> $GITHUB_ENV
          else
            echo "server_running=false" >> $GITHUB_ENV
          fi

      - name: Stop server if running
        if: env.server_running == 'true'
        run: |
          echo "Stopping server running on port 8080..."
          sudo kill -9 $PID
          echo "Preivous running Server stopped."

      - name: Start LTS built server .jar
        run: |
          sudo nohup java -jar backend/build/libs/cruru-0.0.1-SNAPSHOT.jar &
          echo "Lastest Backend API Server started."
