name: BE/CI - Test Coverage 검증

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - be/develop

jobs:
  test-coverage-pr-opened:
    defaults:
      run:
        working-directory: ./backend
    if: startsWith(github.head_ref, 'be-')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties', '**/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: Run tests and generate coverage report
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        run: ./gradlew test jacocoTestReport
        continue-on-error: true

      - name: Verify test coverage
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        run: ./gradlew jacocoTestCoverageVerification
        continue-on-error: true

      - name: 테스트 커버리지를 PR에 코멘트로 등록
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📌 Test Coverage Report
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      - name: Cache Gradle build cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.workspace }}/backend/.gradle/build-cache
          key: ${{ runner.os }}-gradle-build-cache-${{ hashFiles('**/*.gradle*', '**/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-build-cache-

      - name: List Gradle build cache directory
        run: ls -al ${{ runner.workspace }}/2024-cruru/backend/.gradle/build-cache
