name: BE/PM - PR Review 슬랙 알림

on:
  pull_request:
    types: [review_requested]
    branches:
      - main
      - 'be/**'

  pull_request_review:
    types: [submitted]
    branches:
      - main
      - 'be/**'

env:
  Dobby-Kim: "U07BJABU6G1"
  U07BJABU6G1: "BE팀 도비"
  Chocochip101: "U07BUEJDS8G"
  U07BUEJDS8G: "BE팀 초코칩"
  xogns1514: "U07AZ26UC2J"
  U07AZ26UC2J: "BE팀 러쉬"
  cutehumanS2: "U07B88ZQDU4"
  U07B88ZQDU4: "BE팀 냥인"
  HyungHoKim00: "U07B5HBKZM1"
  U07B5HBKZM1: "BE팀 명오"

jobs:
  review-requested_requested:
    if: github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Set reviewer and sender variables
        id: set-vars
        run: |
          echo "REVIEWER_SLACK_ID=${{ env[github.event.requested_reviewer.login] }}" >> $GITHUB_ENV
          echo "SENDER_SLACK_ID=${{ env[github.event.sender.login] }}" >> $GITHUB_ENV

      - name: pr reviewe 요청 시 slack 알림 보내기
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.REVIEW_MENTION_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✨ 리뷰 요청 ✨",
                    "emoji": true
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "${{ github.event.sender.avatar_url }}",
                      "alt_text": ""
                    },
                    {
                      "type": "plain_text",
                      "text": "<@${{ env.SENDER_SLACK_ID }}>",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "➡️ <@${{ env.REVIEWER_SLACK_ID }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "💡*PR 제목:*\n${{ github.event.pull_request.title }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "⚡️ PR 바로가기 ⚡️",
                        "emoji": true
                      },
                      "value": "PR_LINK",
                      "url": "${{ github.event.pull_request.html_url }}",
                      "action_id": "actionId-1"
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
  review-submitted_alert:
    if: github.event.action == 'submitted' && github.event.review.state != 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - name: Set reviewer and reviewee variables
        id: set-vars
        run: |
          echo "REVIEWER_SLACK_ID=${{ env[github.event.sender.login] }}" >> $GITHUB_ENV
          echo "ASSIGNEE_SLACK_ID=${{ env[github.event.pull_request.login] }}" >> $GITHUB_ENV

      - name: pr 리뷰 완료 후 submit되면 reviewee에게 slack 알림 발송
        if: env.ASSIGNEE_SLACK_ID != ''
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.REVIEW_MENTION_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🔥리뷰 완료🔥",
                    "emoji": true
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "${{ github.event.sender.avatar_url }}",
                      "alt_text": ""
                    },
                    {
                      "type": "plain_text",
                      "text": "<@${{ env.REVIEWER_SLACK_ID }}>",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "➡️ <@${{ env.ASSIGNEE_SLACK_ID }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "💡*PR 제목:*\n${{ github.event.pull_request.title }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "⚒️ 받은 리뷰 확인하기 ⚒️",
                        "emoji": true
                      },
                      "value": "PR_LINK",
                      "url": "${{ github.event.pull_request.html_url }}",
                      "action_id": "actionId-1"
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
  pr-approved_alert:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - name: Set assignee variables
        id: set-vars
        run: |
          echo "ASSIGNEE_SLACK_ID=${{ env[github.event.pull_request.assignee.login] }}" >> $GITHUB_ENV

      - name: pr reviewer가 Approve 하면 slack 알림 보냄
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.TASK_COMPLETE_SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🏁 PR 승인 🏁",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "<@${{ env.ASSIGNEE_SLACK_ID }}>님! 리뷰어들에게 승인을 받았어요!"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "🚀 *PR 제목:*\n${{ github.event.pull_request.title }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🕹️ Merge 하러 가기 🕹️",
                        "emoji": true
                      },
                      "value": "PR_LINK",
                      "url": "http://www.d.c",
                      "action_id": "actionId-1"
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
