name: FE/CI - 테스트 실행 및 검증

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - fe/develop

jobs:
  pr-ready:
    runs-on: ubuntu-latest
    steps:
      - name: Set reviewer and sender variables
        id: set-vars
        run: |
          echo "ASSIGNEE_SLACK_ID=${{ env[github.event.pull_request.assignee.login] }}" >> $GITHUB_ENV

      - name: Set reviewer and sender nickname
        id: set-nicks
        run: |
          echo "ASSIGNEE_NICKNAME=${{ env[format('{0}', env.ASSIGNEE_SLACK_ID)] }}" >> $GITHUB_ENV

      - name: pr review 요청 -> 리뷰어에게 slack 멘션 알림
        id: send-message
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.REVIEW_MENTION_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🎁 (#${{ github.event.pull_request.number }}) Pull Request가 준비되었습니다!",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "\n*진행자:*\n${{ env.ASSIGNEE_NICKNAME }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.event.pull_request.title }}*"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "👉🏻 PR 바로가기 👈🏻",
                      "emoji": true
                    },
                    "value": "바로가기 링크",
                    "url": "${{ github.event.pull_request.html_url }}",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ],
              "icon_url": "${{ github.event.sender.avatar_url }}"
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack 메세지 ID를 PR comment에 등록
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ${{ steps.send-message.outputs.ts }}
  run-test-pr-opened:
    if: startsWith(github.head_ref, 'fe-')
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: 저장소 checkout
        uses: actions/checkout@v4

      - name: Node.js 셋업
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            frontend/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 애플리케이션 의존성 항목들 설치
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 백엔드 API 연동용 환경변수 설정
        run: |
          echo "REACT_APP_CRURU_API_URL=${{ secrets.API_URL }}" >> .env.production

      - name: 애플리케이션 기능 테스트
        run: npm run test -- --passWithNoTests
