name: issue - branch Create Automation

on:
  issues:
    types: [opened, assigned]

jobs:
  create-issue-branch:
    name: "create issue branch"
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@main
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-PR-link-comment:
    name: "create Draft PR Link on issue"
    runs-on: ubuntu-latest
    steps:
      - name: choose a pr template
        if: steps.create-issue-branch.outputs.branchName != ''
        id: template
        env:
          BRANCH_NAME: ${{ steps.create-issue-branch.outputs.branchName }}
        run: |
          branch=$BRANCH_NAME
          template="pull_request_template.md"
          echo "::set-output name=template-name::$template";
          echo "${{ steps.create-issue-branch.outputs }}"

      - name: add pr link in comment
        uses: mshick/add-pr-comment@main
        if: steps.create-issue-branch.outputs.branchName != ''
        env:
          PULL_REQUEST_URL: ${{ github.event.issues.issue.pull_request.url }}
          TEMPLATE: pull_request_template.md
          SOURCE_BRANCH: ${{ steps.create-issue-branch.outputs.branchName }}

        with:
          message: |
            ## Pull Request ![](https://raw.githubusercontent.com/primer/octicons/master/icons/git-pull-request-16.svg)

            ${{ SOURCE_BRANCH }} -> develop Draft PR이 생성되었습니다!
            [이슈와 연결된 PR 바로가기](${{ env.PULL_REQUEST_URL }}).
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
