name: pm / issues

on:
  issues:
    types: [opened, assigned]

permissions:
  issues: write
  contents: write
  repository-projects: write
  pull-requests: write
  
env:
  PROJECT_BOARD: "2024-cruru"
  ICEBOX_OPTION: "TODO"
  STARTED_OPTION: "In Progress"
  BEFORE_REVIEW_COLUMN_OPTION: "Pending"

jobs:
  add-issue-to-project-board:
    name: "add issue to project board"
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'assigned'
    steps:
      - name: get column name
        id: column
        run: |
          if [[ "${{ github.event.action }}" == "assigned" ]]; then \
            echo "::set-output name=column-name::${{ env.STARTED_OPTION }}"; \
          else \
            echo "::set-output name=column-name::${{ env.ICEBOX_OPTION }}"; \
          fi

      - name: add issue to column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: ${{ env.PROJECT_BOARD }}
          column: ${{ steps.column.outputs.column-name }}
          repo-token: ${{ secrets.PAT_TEST_B }}

  create-issue-branch:
    name: "create issue branch"
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@main
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: choose a pr template
        if: steps.create-issue-branch.outputs.branchName != ''
        id: template
        env:
          BRANCH_NAME: ${{ steps.create-issue-branch.outputs.branchName }}
        run: |
          branch=$BRANCH_NAME
          template="pull_request_template.md"
          echo "::set-output name=template-name::$template"

      - name: add pr link in comment
        uses: mshick/add-pr-comment@main
        if: steps.create-issue-branch.outputs.branchName != ''
        env:
          PULL_REQUEST_URL: ${{ format('https://github.com/{0}/compare/{1}...{2}?quick_pull=1&template={3}', github.repository, github.event.repository.default_branch, steps.create-issue-branch.outputs.branchName, steps.template.outputs.template-name) }}
          TEMPLATE: ${{ steps.template.outputs.template-name }}
        with:
          message: |
            ## Pull Request ![](https://raw.githubusercontent.com/primer/octicons/master/icons/git-pull-request-16.svg)

            [Create a pull request](${{ env.PULL_REQUEST_URL }}) for the issue branch using the `${{ env.TEMPLATE }}` template.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
