name: mention-to-slack-actions

on:
  pull_request:
    branches: [ "be/develop", "fe/develop" ]
    types: [ opened, review_requested, ready_for_review ]
  pull_request_review:
    types: [ submitted ]
#  pull_request_review_comment: 기능 추가 예정
#    types: [created, edited]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Mention to Slack Actions
        uses: Laurenfrost/mention-to-slack@latest
        with:
          configuration-path: .github/mention-to-slack.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
