name: Send mention to Request Review

on:
  workflow_dispatch:
  pull_request:
    types: [review_requested]

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files for debugging
        run: ls -R .github/workflows/

      - name: Get Reviewers List
        id: reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const filePath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'workflows', 'reviewers.json');
            const workers = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            const mention = context.payload.pull_request.requested_reviewers.map((user) => {
              const login = user.login;
              const mappedValue = workers[login];
              return mappedValue ? `<@${mappedValue}>` : `No mapping found for ${login}`;
            });
            return mention.join(', ');
          result-encoding: string

      - name: pr reviewer 되면 slack 알림 보냄
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.TEST_CHANNEL }}
          payload: |
            {
              "text": "pr review request",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.reviewers.outputs.result }}\\n 🚀 리뷰어로 요청이 왔습니다!\\n ✨제목: ${{ github.event.pull_request.title }}\\n \\n • 링크: <${{ github.event.pull_request.html_url }}|PR 확인하러 가기>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
